### ISSUE TITLE
Shellcheck Invalid configuration Fix Configuration

### ISSUE THREAD

**Issue by empereira** [pwielgolaski/shellcheck-plugin#10]
Hello,

I have pycharm on ubuntu and installed shellcheck, but the shellcheck invalid configuration error message appears.

I tried configuring it according to the "fix configuration" option, but the request appears to be an ".exe". Does this plugin only work on Windows?

**Comment by pwielgolaski** [comment]
Ubuntu is supported
![Screenshot from 2019-04-22 18-07-43](https://user-images.githubusercontent.com/3696319/56510318-b8ccba00-6529-11e9-8363-94aa3091b2df.png)

I agree that naming could be more misleading
