### ISSUE TITLE
Only one letter is highlighted as a warning

### ISSUE THREAD

**Issue by singalen** [pwielgolaski/shellcheck-plugin#3]
Thanks for integrating the fantastic tool into IDEA!

I get only 1 letter highlighted for warningns were SC2046 and SC2034.

This looked like [shellcheck's API](https://github.com/koalaman/shellcheck/wiki/Integration) limitation, but apparently they already have `endColumn` implemented: https://github.com/koalaman/shellcheck/issues/1262

So far, a workaround for those without `endColumn` would be to highlight a word if the warning position is a word start. I'm not asking to do syntax analysis for subshells in `$()`.

**Comment by pwielgolaski** [comment]
could you share some screenshot of the issue?

**Comment by singalen** [comment]
I don't have that very script now, but here's another one:
![screenshot 2018-08-20 15 42 23](https://user-images.githubusercontent.com/151199/44370589-b6442d00-a48f-11e8-9594-2fea5429fc41.png)

**Comment by pwielgolaski** [comment]
I don't want to make custom logic for it, you can get whole line highlight in option.
I added support for latest version of shellcheck, so if I get endcolumn it is highlighted correctly
