### ISSUE TITLE
Crash with version 0.1.2

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [pwielgolaski/shellcheck-plugin#6]
@pwielgolaski 
The commit 09fe47a34b593d6eee87c41383b99add6eeb3fa6 has introduced a bug. The plugin crashes with an invalid annotation range:
<img width="936" alt="screen shot 2019-03-01 at 5 28 35 pm" src="https://user-images.githubusercontent.com/278624/53620569-8dbf9b80-3c47-11e9-97f1-991297dafcf1.png">

Shellcheck version 0.6.0
IntelliJ Ultimate 2018.3.4
Mac OS 10.14.3

**Comment by pwielgolaski** [comment]
Could you sample input so I could reproduce it?

**Comment by pwielgolaski** [comment]
fix done and new version released, just wait for JetBrains to approve it and make it public

**Comment by hubertgrzeskowiak** [comment]
Wow, that was quick! Cheers, mate

**Comment by hubertgrzeskowiak** [comment]
Installed from disk. Can confirm it works flawlessly now
